name: release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Semantic version tag to stamp on release and source'
        type: string
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - name: Deploy
        uses: azure/CLI@v1
        with:
          azcliversion: 2.51.0
          inlineScript: |
            az config set bicep.use_binary_from_path=False
            az bicep install
            az bicep build -f ./tests/main.bicep
      - name: Create release
        run: gh release create ${{env.tag}} './main.json' -p --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}